services:

  grafana:
    container_name: grafana-v11
    image: 'grafana/grafana:11.2.0'
    ports:
      - '3000:3000'
    environment:
      GF_SECURITY_ADMIN_USER: 'admin'
      GF_SECURITY_ADMIN_PASSWORD: '12345678'
      GF_LOG_LEVEL: 'info'
      GF_INSTALL_PLUGINS: 'grafana-clock-panel,grafana-simple-json-datasource'
    volumes:
      - type: volume
        source: grafana_data
        target: /var/lib/grafana
    restart: unless-stopped

  prometheus:
    container_name: prometheus-v2
    image: 'prom/prometheus:v2.54.1'
    ports:
      - '9090:9090'
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--web.enable-lifecycle'
    volumes:
      - type: volume
        source: prometheus_data
        target: /prometheus
      - type: bind
        source: prometheus.yaml
        target: /etc/prometheus/prometheus.yaml
    restart: unless-stopped

  pushgateway:
    container_name: pushgateway-v1
    image: 'prom/pushgateway:v1.9.0'
    ports:
      - '9091:9091'
    restart: unless-stopped


volumes:
  grafana_data:
    external: false
  prometheus_data:
    external: false
