global:
  scrape_interval: 10s
  scrape_timeout: 10s
  evaluation_interval: 60s

scrape_configs:
  - job_name: 'prometheus'
    scrape_interval: 10s
    static_configs:
      - targets: ['localhost:9090']
        labels:
          group: 'poc'
  - job_name: 'go-client'
    static_configs:
      - targets: ['host.docker.internal:8080']
        labels:
          group: 'poc'
